[general]
	import = [
		"~/.config/alacritty/themes/catppuccin-mocha.toml"
	]
[env]
	TERM="xterm-256color"
[window]
	decorations="Full"
	opacity=0.95
	blur=true
	startup_mode="Maximized"

[font]
	normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
	size = 13

